language: python
python:
  - "2.7.13"
  - "3.6"
install:
  - pip install pytest pytest-cov mock
  - pip install -r requirements.txt
script:
  - pytest -v --junitxml unittests.xml --cov=pyxpiral --cov-config .coveragerc --cov-report xml --cov-report term
  - pylint -f parseable --rcfile=.pylintrc mypackage | tee pylint.out